config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "user/registrations" }

  
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#dashboard', as: :authenticated_root
    end
    
    
    
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  root 'devise/sessions#new'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_users', to: 'pages#all_users'
  get 'my_recipes', to: "recipes#my_recipes"
  get 'search_ingredients', to: "ingredients#search"
  get 'search_materials', to: "materials#search"
  
  get "recipe/new_release" => 'recipe#new_release', :as => :new_release
  
  resources :ingredients
  
  resources :recipes
    
  resources :recipe_ingredients

  resources :overheads
  
  resources :materials
  
  resources :recipe_materials
  
  resources :users#, only: [:index, :edit, :update]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    
    belongs_to :user
    has_many :recipe_ingredients, dependent:  :destroy
    has_many :ingredients, through: :recipe_ingredients, :class_name => 'Ingredient'
    
    has_many :recipe_materials, dependent:  :destroy
    has_many :materials, through: :recipe_materials, :class_name => 'Material'
    
    validates :serving_number, presence: true, :numericality => { :greater_than => 0 }
    validates :time_spent_in_hour, presence: true, :numericality => { :greater_than => 0 }
    validates :rate_per_hour, :numericality => { :greater_than => 0 }
    validates :percentage_profit, :numericality => { :greater_than => 0 }
    
    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 3, maximum: 50}
    validate :image_size
    
    mount_uploader :image, PictureUploader
    
   accepts_nested_attributes_for :recipe_ingredients, :allow_destroy => true, reject_if: :all_blank
   accepts_nested_attributes_for :ingredients, reject_if: :all_blank
   
    accepts_nested_attributes_for :recipe_materials, :reject_if => :all_blank, :allow_destroy => true
   accepts_nested_attributes_for :materials, :reject_if => :all_blank
   
   
    def reject_recipe_item(attributed)
        attributed[:name].blank?
    end

   
   def calculate_cost
    total = 0
    self.recipe_ingredients.each do |recipe_ingredient| 
            cost = (recipe_ingredient.ingredient_price.to_f * recipe_ingredient.quantity.to_f)
            total = total + cost
    end
    self.cost = total
    self.save
   end
   
    def calculate_material_cost
        total = 0
        self.recipe_materials.each do |recipe_material| 
                cost = (recipe_material.material_price.to_f * recipe_material.quantity.to_f)
                total = total + cost
        end
        self.material_cost = total
        self.save
    end
   
  
  private
  
  def image_size
    if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
    end
  end
   
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   
    before_action :set_recipe, only: [:edit, :update, :destroy]
   
    def my_recipes
        @recipes = current_user.recipes.paginate(page: params[:page], per_page: 9)
        
    end
    
    
    def index
        #@recipes = current_user.recipes.paginate(page: params[:page], per_page: 6)
        @recipes = current_user.recipes
    end
    
    def new
        @recipe = Recipe.new
    end
    
    def edit
        #@recipe.recipe_ingredients.build
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.user = current_user
        #@recipe = current_user.recipes.build(recipe_params)
        
        unless @recipe.recipe_ingredients.nil?
            @recipe.recipe_ingredients.each do |f|
                
                unless f.ingredient.nil?
                    f.ingredient.user = current_user
                end
            end
        end
        
        unless @recipe.recipe_materials.nil?
            @recipe.recipe_materials.each do |f|
                
                unless f.material.nil?
                    f.material.user = current_user
                end
            end
        end
        
        
        begin
            if @recipe.save
            flash[:notice] = "Recipe was successfully created"
            redirect_to recipe_path(@recipe)
            else
                flash[:danger] = "Recipe cannot be created"
                render 'new'
            end
        rescue ActiveRecord::RecordNotUnique
            respond_to do |format|
            format.html { render :action => 'new' }
            format.html
            flash[:danger] = "Unable to proceed because there were same ingredient being used"
            end
        end
    end
    

    
    def update
       #@recipe.cost = @recipe.calculate_cost
       #@recipe.ingredients.build
        
        unless @recipe.recipe_ingredients.nil?
            @recipe.recipe_ingredients.each do |f|
                
                unless f.ingredient.nil?
                    f.ingredient.user = current_user
                end
            end
        end
        
        
        if @recipe.recipe_materials.nil?
        else
            @recipe.recipe_materials.each do |f|
                
                if f.material.nil?
                else
                    f.material.user = current_user
                end
            end
        end
        
       if @recipe.update(recipe_params)
           flash[:notice] = "Recipe was successfully updated"
           redirect_to recipe_path(@recipe)
       else
           render 'edit'
       end
    end
    
    
    def show
        @recipe_ingredient = RecipeIngredient.new
        #@ingredient = @recipe_ingredient.ingredients.build
        #@ingredient = Ingredient.new
        @ingredients = current_user.ingredients
        @materials = current_user.materials
        @recipe = Recipe.includes(:recipe_ingredients, :recipe_materials).find(params[:id])
        @recipe.calculate_cost
        @recipe.calculate_material_cost
        @labour = ((@recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*@recipe.time_spent_in_hour.to_f)
        @cake_cost = (@recipe.cost.to_f + @recipe.material_cost.to_f + ((@recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*@recipe.time_spent_in_hour.to_f))
        @profit = (@recipe.percentage_profit.to_f/100)*@cake_cost.to_f
        @total = @profit.to_f + @cake_cost.to_f
    end
    
    def destroy
        @recipe.destroy
        flash[:notice] = "Recipe was successfully deleted"
        #redirect_to recipes_path
        redirect_to recipes_path
    end
    
    def new_release
        respond_to do |format|
        format.html
        format.js
        end
    end
    
    private
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end
    
    def recipe_params
        #params.require(:recipe).permit(:id, :title, :image, :description, :instructions, :rate_per_hour, :time_spent_in_hour, :percentage_profit, :_destroy, recipe_ingredients_attributes: [:id, :_destroy, :ingredient_id, :quantity, ingredient_attributes: [:id, :name, :purchase_price, :volume, :unit, :_destroy]])
        params.require(:recipe).permit(:id, :title, :image, :description, :instructions, :rate_per_hour, :time_spent_in_hour, :percentage_profit, :serving_number, :_destroy, 
        recipe_ingredients_attributes: [:id, :_destroy, :recipe_id, :ingredient_id, :quantity, ingredient_attributes: [:id, :name, :purchase_price, :volume, :unit, :user_id, :_destroy]],
        recipe_materials_attributes: [:id, :_destroy, :recipe_id, :material_id, :quantity, material_attributes: [:id, :material_name, :purchase_price, :purchase_quantity, :user_id, :_destroy]])
        
        
    end
    
    
end

app/views/recipes/_field_fields.html.erb
<fieldset>
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
      <%= f.fields_for :ingredient do |h| %>
        <%= h.label :name %>
        <%= h.text_field :name %>
        
        <%= h.label :purchase_price %>
        <%= h.number_field :purchase_price %>
        
        <%= h.label :purchase_quantity %>
        <%= h.number_field :volume %>
        
        <%= h.label :unit %>
        <%= h.text_field :unit %>
      <% end %>
      <%= link_to "[remove]", '#', class: "remove_fields" %>
</fieldset>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-md-10">
    <div class = "panel panel-default" style="background-color:#ffffff">
      <div class="panel-body">
        
        
        <% if@recipe.errors.any? %>
        <div class="row">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <h2 class="panel-title">
                  <%= pluralize(@recipe.errors.count, "error") %>
                  prohibited this recipe from being saved:
                </h2>
                <div class="panel-body">
                  <ul>
                    <% @recipe.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
        </div>
        <% end %>
  
        
      <%= simple_form_for @recipe, defaults: {input_html: {multipart: true, class:'form-horizontal'}}  do |f| %>
      
        <%= f.input :title, validate: { presence: true, uniqueness: false } ,hint: 'Recipe Name ', input_html: {class: 'form-control'} %>
        <br>
        <%#= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', input_html: {class: 'form-control'} %>
        <br>
        <%= f.input :description, input_html: {rows:'3', class: 'form-control'} %>
        <br>
        <div class="row">
        <div class="col-md-3 no-padding">
          <%= f.input :serving_number, input_html: {class: 'form-control', min: 0}, hint: 'Approximate number of serving.' %></div>
        <div class="col-md-3 no-padding left-padding">
          <%= f.input :rate_per_hour, input_html: {class: 'form-control', min: 0}, hint: 'Your hourly wage.' %></div>
        <div class="col-md-3 no-padding left-padding">
          <%= f.input :time_spent_in_hour, input_html: {class: 'form-control', min: 0}, hint: 'Time taken for you to make this recipe(etc 1 is equavalent to 1 hour / 0.5 is equavalent to 30 minutes.' %></div>
        <div class="col-md-3 no-padding left-padding">
          <%= f.input :percentage_profit, input_html: {class: 'form-control', min: 0}, label: 'Optional percentage profit to add', hint: 'Value in percentage(%).' %>
        </div></div>
        <br><br>
        
        
        <div class="row">
        <div class="container-fluid">
          <ul class="nav nav-tabs nav-justified">
            <li class="active"><a href="#Ingredient" data-toggle="tab"><strong>Ingredients</strong></a></li>
            <li><a href="#Material" data-toggle="tab"><strong>Non-food items/Material</strong></a></li>
          </ul>
          
          <div class="tab-content">
            <div class="tab-pane fade in active" id="Ingredient">
                <h2><strong>Ingredients</strong></h2>
                <div class= "table-responsive">
                  <table class="table">
                    <thead>
                      <th>Quantity</th>
                      <th>Ingredient Name</th>
                      <th>Purchase Price</th>
                      <th>Purchase Quantity</th>
                      <th>unit</th>
                    </thead>
                    <tbody id="recipe_ingredients">
                      <%= f.simple_fields_for :recipe_ingredients, defaults: {input_html: {class:'form-inline'}} do |recipe_ingredient| %>
                        <%= render 'recipe_ingredient_fields', :f => recipe_ingredient %>
                      <% end %>
                      <%#= link_to_add_association 'Add an Ingredient',f, :recipe_ingredients, :"data-association-insertion-node" => "tbody#recipe_ingredients", :"data-association-insertion-method" => "append", :partial => "recipe_ingredient_fields", :class => "btn btn-default" %>
                    </tbody>
                    
                  </table>
                  </div>
                <%= link_to_add_association 'Add an Ingredient',f, :recipe_ingredients, :"data-association-insertion-node" => "tbody#recipe_ingredients", :"data-association-insertion-method" => "append", :partial => "recipe_ingredient_fields", :class => "btn btn-default custom-small-button" %>
                    
            </div>
            <div class="tab-pane fade in" id="Material">
                <h2><strong>Non-food items</strong></h2>
                <div class= "table-responsive">
                  <table class="table">
                    <thead>
                      <th>Quantity</th>
                      <th>Material Name</th>
                      <th>Purchase Price</th>
                      <th>Purchase Quantity</th>
                    </thead>
                    <tbody id="recipe_materials">
                      <%= f.simple_fields_for :recipe_materials, defaults: {input_html: {class:'form-inline'}} do |recipe_material| %>
                        <%= render 'recipe_material_fields', :f => recipe_material %>
                      <% end %>
                      <%#= link_to_add_association 'Add an Ingredient',f, :recipe_ingredients, :"data-association-insertion-node" => "tbody#recipe_ingredients", :"data-association-insertion-method" => "append", :partial => "recipe_ingredient_fields", :class => "btn btn-default" %>
                    </tbody>
                    
                  </table>
                </div>
                <%= link_to_add_association 'Add Material',f, :recipe_materials, :"data-association-insertion-node" => "tbody#recipe_materials", :"data-association-insertion-method" => "append", :partial => "recipe_material_fields", :class => "btn btn-default custom-small-button" %>
              
            </div>
          </div>
        </div>
        </div>
        
        <br>
        
        <div class="pull-right">
            <%= link_to 'Cancel', recipes_path, class: "btn btn-default custom-cancel-button" %>
            <%= f.button :submit, :disable_with => 'Please wait ...', :class => 'custom-main-button' %>
        </div>
        
      <% end %>
      </div>
      </div>
   </div>
</div>

app/views/recipes/_ingredient_fields.html.erb
<td class="nested-fields">
  <%#= f.label :new_ingredient_name %>
  <%#= f.text_field :name, class: "form-control" %>
  <%= f.input :name,required: true, label: false, placeholder: "New Ingredient Name", input_html: {class:'form-control', required: true } %>
  <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id } %>
</td>

app/views/recipes/_ingredient_list.html.erb
<% f.each do |ingredient| %>
        <tr>
        <td><%= ingredient.name %></td>
        <td><%= number_to_currency(ingredient.purchase_price, :unit => "RM") %></td>
        <td><%= ingredient.volume %></td>
        <td><%= ingredient.unit %></td>
        <td><%= number_to_currency(ingredient.price, :unit => "RM") %></td>
        <td>
            <%= link_to "Add to this recipe", recipe_ingredients_path(recipe_id: g.id, ingredient_id: ingredient.id), class: 'btn btn-sm custom-small-new-button', method: :post %>
            
        </td>
        </tr>
<% end %> 

app/views/recipes/_recipe.html.erb
<div class="col-md-4 blog-main box text-center" id="recipe_<%= recipe.id %>">
    
        <div class="panel panel-info">
        <% recipe.calculate_cost %>
        <% recipe.calculate_material_cost %>
        
        

            <div class="panel-heading panel-heading-grid">
                <h3 class="panel-title"><strong><%= recipe.title %></strong></h3>
                <br>
                <h3 class="panel-title"><strong><%#= link_to "#{recipe.title}", recipe_path(recipe.id)%></strong></h3>
                <%#= image_tag recipe.image.url, size: "100x100" %>
                <p><%= recipe.description %></p>
                <br><br>
                <table class="table">
                    <tbody>
                        <tr>
                            <td>Ingredient Cost : </td>
                            <td><%= number_to_currency(recipe.cost, :unit => "RM") %></td>
                        </tr>
                        <tr>
                            <td>Non-food Cost(Materials) : </td>
                            <td><%= number_to_currency(recipe.material_cost, :unit => "RM") %></td>
                        </tr>
                        <tr>
                            <td><strong>Grant Cost of Recipe : </strong></td>
                            <td><strong><%= number_to_currency(recipe.cost.to_f + recipe.material_cost.to_f, :unit => "RM") %></strong></td>
                        </tr>
                        <tr>
                            <td>Labour Cost</td>
                            <td><% @labour = ((recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*recipe.time_spent_in_hour.to_f) %>
                            <%= number_to_currency(@labour, :unit => "RM") %>
                            </td>
                        </tr>
                        <tr>
                            <td>Recipe cost</td>
                            <td><% @cake_cost = (recipe.cost.to_f + recipe.material_cost.to_f + ((recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*recipe.time_spent_in_hour.to_f)) %>
                            <%= number_to_currency(@cake_cost, :unit => "RM") %>
                            </td>
                        </tr>
                        <tr>
                            <td>Profit to add to price:</td>
                            <td><% @profit = (recipe.percentage_profit.to_f/100)*@cake_cost.to_f %>
                            <%= number_to_currency(@profit, :unit => "RM") %>
                            </td>
                        </tr>
                        <tr><% @total = @profit.to_f + @cake_cost.to_f %>
                            <td>TOTAL cost of RECIPE(S) including profit:</td>
                            <td><%= number_to_currency(@total, :unit => "RM") %></td>
                        </tr>
                        <tr>
                            <td>Number of serving</td>
                            <td><%= recipe.serving_number %></td>
                        </tr>
                        <tr>
                            <td>Cost per serving</td>
                            <td><%= number_to_currency(@total.to_f / recipe.serving_number.to_f, :unit => "RM") %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class="panel-body">
            
                <div class="btn-group" role="group" aria-label="..." >
                    <%= link_to 'Edit', edit_recipe_path(recipe.id), :class => "btn btn-default" %>
                    <%= link_to 'View', recipe_path(recipe.id), :class => "btn btn-default" %>
                    <%= link_to 'Delete', recipe_path(recipe.id), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-default btn-danger' %>
                </div>
            </div>
        </div>
</div>

app/views/recipes/index.html.erb
<%- model_class = Recipe -%>



<div class= "row">
  <div class = "container col-md-10">
    <div class="page-header">
      <h1><i class="fa fa-cutlery" aria-hidden="true"></i> Recipes 
          <div class = "pull-right">
            <%= link_to raw("<i class=\"fa fa-th\" aria-hidden=\"true\"> Grid</i>"), 
                    my_recipes_path, 
                    class: "btn btn-default" %>
                    <%= link_to 'Add Recipe', new_recipe_path, :class => 'btn custom-new-button' %>
          </div>
      </h1>
    </div>
      <br>
      <br>
      <div align="center">
          <%#= will_paginate %>
      </div>
      
      <div class="panel panel-default">
      	<div class="panel-heading panel-heading-custom">
      		List of Recipes
      	</div>
      	<div class="panel-body">
      	  <div class="table-responsive">
          <table class="table" id="recipes">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th>Ingredients Cost</th>
                <th>Non-food item cost (Materials)</th>
                <th>Grant cost of Recipe</th>
                <th>Labour Cost</th>
                <th>Recipe cost</th>
                <th>Profit to add to price:</th>
                <th>TOTAL cost of RECIPE(S) including profit:</th>
                <th>Number of serving</th>
                <th>Cost per serving</th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @recipes.each do |recipe| %>
                <tr>
                  <% @recipe = Recipe.includes(:recipe_ingredients).find(recipe.id) %>
                  <% recipe.calculate_cost %>
                  <% recipe.calculate_material_cost %>
                  <td><%= link_to recipe.title, recipe_path(recipe) %></td>
                  <td><%= number_to_currency(recipe.cost, :unit => "RM") %></td>
                  <td><%= number_to_currency(recipe.material_cost, :unit => "RM") %></td>
                  <td><%= number_to_currency(recipe.cost.to_f + recipe.material_cost.to_f, :unit => "RM") %></td>
                  
                  
                        
                            
                            <td><% @labour = ((recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*recipe.time_spent_in_hour.to_f) %>
                            <%= number_to_currency(@labour, :unit => "RM") %>
                            </td>
                        
                            
                            <td><% @cake_cost = (recipe.cost.to_f + recipe.material_cost.to_f + ((recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*recipe.time_spent_in_hour.to_f)) %>
                            <%= number_to_currency(@cake_cost, :unit => "RM") %>
                            </td>
                       
                            
                            <td><% @profit = (recipe.percentage_profit.to_f/100)*@cake_cost.to_f %>
                            <%= number_to_currency(@profit, :unit => "RM") %>
                            </td>
                        
                            <% @total = @profit.to_f + @cake_cost.to_f %>
                            
                            <td><%= number_to_currency(@total, :unit => "RM") %></td>
                        
                            
                            <td><%= recipe.serving_number %></td>
                        
                            
                            <td><%= number_to_currency(@total.to_f / recipe.serving_number.to_f, :unit => "RM") %></td>
                                          
                  
                  <td>
                          
                    <%= link_to '', edit_recipe_path(recipe), :class => 'btn btn-default btn-xs fa fa-pencil-square-o'%>
                    <%= link_to '', recipe_path(recipe), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-xs btn-danger fa fa-trash' %>
                    
                    <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                recipe_path(recipe),
                                :method => :delete,
                                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                :class => 'btn btn-xs btn-danger' %>
                  </td>
                </tr>
          
              <% end %>
            </tbody>
          </table>
          </div>
      	</div>
      </div>
      
      
      
          
      <div align="center">
          <%#= will_paginate %>
      </div>

  </div>
</div>

app/views/recipes/show.html2.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dd><%= image_tag(@recipe.image.url, size: "250x150") if @recipe.image? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @recipe.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @recipe.description %></dd>
  
 



    <h3>Ingredients</h3><%#= render 'ingredients/popup' %>
    <table class = "table table-condensed">
      <thead>
        <tr>
          <td><strong>Ingredients</strong></td>
          <td><strong>Unit</strong></strong></td>
          <td><strong>Quantity</strong></td>
          <td><strong>Cost to buy ingredients</strong></td>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
        <tr>
          <td><%#= recipe_ingredient.ingredient_name %> <%= link_to "#{recipe_ingredient.ingredient_name}", ingredient_path(recipe_ingredient.ingredient_id)%></td>
          <td><%= recipe_ingredient.ingredient_unit %></td>
          <td><%= recipe_ingredient.quantity %></td>
          <td><%= number_to_currency(recipe_ingredient.ingredient_price.to_f * recipe_ingredient.quantity.to_f, :unit => "RM") %></td>
        </tr>
        <% end %>
        <tr>
          <td colspan="3" align="right"><strong>Total ingredients cost</strong></td>
          <td colspan="1"><strong><%= number_to_currency(@recipe.cost, :unit => "RM") %></strong></td>
        </tr>
      </tbody>
    </table>
    
    
    <h3>Materials</h3><%#= render 'ingredients/popup' %>
    <table class = "table table-condensed">
      <thead>
        <tr>
          <td><strong>Materials</strong></td>
          <td><strong>Quantity</strong></td>
          <td><strong>Cost to buy materials</strong></td>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_materials.each do |recipe_material| %>
        <tr>
          <td><%#= recipe_ingredient.ingredient_name %> <%= link_to "#{recipe_material.material_material_name}", ingredient_path(recipe_material.material_id)%></td>
          <td><%= recipe_material.quantity %></td>
          <td><%= number_to_currency(recipe_material.material_price.to_f * recipe_material.quantity.to_f, :unit => "RM") %></td>
        </tr>
        <% end %>
        <tr>
          <td colspan="2" align="right"><strong>Total materials cost</strong></td>
          <td colspan="1"><strong><%= number_to_currency(@recipe.material_cost, :unit => "RM") %></strong></td>
        </tr>
      </tbody>
    </table>
    
 <h3>Summary</h3>   
  <div class="row">
    <div class="col-md-3"><strong>Rate Per Hour:</strong></div>
    <div class="col-md-1 text-right"><%= number_to_currency(@recipe.rate_per_hour, :unit => "RM") %></div>
  </div>
  <div class="row">
    <div class="col-md-3"><strong>Time spent in hour:</strong></div>
    <div class="col-md-1 text-right"><%= @recipe.time_spent_in_hour %></div>
  </div>
  <div class="row">
    <div class="col-md-3"><strong>Overhead Cost Per Hour:</strong></div>
    <div class="col-md-1 text-right"><%= number_to_currency(Overhead.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f), :unit => "RM") %></div>
    <div class="col-md-6 text-right"><strong>Labour Cost:</strong></div>
    <div class="col-md-1 text-right"><%= number_to_currency(@labour, :unit => "RM") %></div>
  </div>
    <div class="row"><br>
    <div class="col-md-3"><strong>Percentage profit to add:</strong></div>
    <div class="col-md-1 text-right"><%= number_to_percentage(@recipe.percentage_profit) %></div>
    <div class="col-md-6 text-right"><strong>Profit to add to price:</strong></div>
    <div class="col-md-1 text-right"><%= number_to_currency(@profit, :unit => "RM") %></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-10 text-right"><strong>Ingredients Cost:</strong></div>
    <div class="col-md-1 text-right"><%= number_to_currency(@recipe.cost, :unit => "RM") %></div>
  </div>
  <div class="row">
    <div class="col-md-10 text-right"><strong>Total Cost of CAKE(S):</strong></div>
    <div class="col-md-1 text-right"><%= number_to_currency(@cake_cost, :unit => "RM") %></div>
  </div>
  <div class="row">
    <div class="col-md-10 text-right"><strong>TOTAL cost of cake including profit:</strong></div>
    <div class="col-md-1 text-right"><strong><%= number_to_currency(@total, :unit => "RM") %></strong></div>
  </div>




<%= link_to t('.back', :default => t("helpers.links.back")),
              recipes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recipe_path(@recipe), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recipe_path(@recipe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>