config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "user/registrations" }

  
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#dashboard', as: :authenticated_root
    end
    
    
    
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  root 'devise/sessions#new'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_users', to: 'pages#all_users'
  get 'my_recipes', to: "recipes#my_recipes"
  get 'search_ingredients', to: "ingredients#search"
  get 'search_materials', to: "materials#search"
  
  get "recipe/new_release" => 'recipe#new_release', :as => :new_release
  
  resources :ingredients
  
  resources :recipes
    
  resources :recipe_ingredients

  resources :overheads
  
  resources :materials
  
  resources :recipe_materials
  
  resources :users#, only: [:index, :edit, :update]

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
    
    belongs_to :user
    has_many :recipe_ingredients, dependent:  :destroy, inverse_of: :ingredient
    has_many :recipes, through: :recipe_ingredients
    # validates :user_id, presence: true
    validates :name, presence: true, length: { minimum: 3, maximum: 50}
    #validates_uniqueness_of :name    #sebab banyak user
    validates :purchase_price, presence: true, :numericality => { :greater_than => 0 }
    validates :volume, presence: true, :numericality => { :greater_than => 0 }
    validates :unit, presence: true
    
   #accepts_nested_attributes_for :recipe_ingredients, reject_if: :all_blank, allow_destroy: true
   
    before_create do |calc_price|
    calc_price.price = self.purchase_price.to_f / self.volume.to_f
    end
    
    before_update do |calc_price|
    calc_price.price = self.purchase_price.to_f / self.volume.to_f
    end
   
   def calculate_price_per_unit
   self.purchase_price.to_f / self.volume.to_f
   end
   
   def find_by_name(ingredient_name)
       where(name: ingredient_name).first
   end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    
    before_action :set_ingredient, only: [:edit, :update, :show, :destroy]
    respond_to :html, :json, :js
    
    def search
        if params[:ingredient]
           @ingredient = Ingredient.find_by_name(params[:ingredient]) 
        end
        
        if @ingredient
            #render json: @ingredient
            render partial: 'lookup'
        else
           render status: :not_found, nothing: true
        end
    end
    
    
    def index
       @ingredient = Ingredient.new
       @ingredients = current_user.ingredients
    end
    
    def new
        @ingredient = Ingredient.new
    end
    
    def edit
    end
    
    def create
        @ingredient = Ingredient.new(ingredient_params)
        @ingredient.user = current_user
        respond_to do |format|
            if @ingredient.save 
                format.html { redirect_to @ingredient, notice: "Ingredient was successfully created" }
                format.json {render :show, status: :created, location: @ingredient }
                format.js 
                
            else
                format.html {render 'new'}
                format.json {render json: @ingredient.errors, status: :unprocessable_entity }
                format.js 
            end
        end
    end
    
    def update
        @ingredient.price = @ingredient.calculate_price_per_unit
        
        respond_to do |format|
            if @ingredient.update_attributes(ingredient_params)
                format.html { redirect_to @ingredient, notice: "Ingredient was successfully updated" }
                format.json {respond_with_bip(@ingredient) }
                #format.json {render :show, status: :ok, location: @ingredient }
                format.js {render layout: false}
                
            else
                format.html {render 'edit'}
                format.json {respond_with_bip(@ingredient) }
                format.js {render layout: false}
            end
        end
    end
    
    def show
        @ingredient.price = @ingredient.calculate_price_per_unit
    end
    
    def destroy
        @ingredient.destroy
        respond_to do |format|
           format.html { redirect_to ingredients_path, notice: "Ingredient was successfully deleted"}
           format.json { head :no_content}
           format.js
        end
    end
    
   
    private
    def set_ingredient
        @ingredient = Ingredient.find(params[:id])
    end
    
   
    
    def ingredient_params
        params.require(:ingredient).permit(:name, :purchase_price, :volume, :unit, :price)
    end
    
end

app/views/ingredients/_form.html.erb
<% if@ingredient.errors.any? %>
<h2>The following errors prevented the ingredient from getting created</h2>
<ul>
    <% @ingredient.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>
<div class= "panel-body">
<%= form_for @ingredient, :html => {:class => 'form-horizontal'} do |f| %>
    <div class = "form-horizontal">
        <p>
            <%= f.label :ingredient_name%>
            <%= f.text_field :name, class: "form-control"%>
        </p>
        
        <p>
            <%= f.label :purchase_price %>
            <%= f.number_field :purchase_price, step: 'any', class:"form-control" %>
        </p>
        
        <p>
            <%= f.label :purchase_weight_or_volume %>
            <%= f.number_field :volume, class:"form-control" %>
        </p>
        
        <p>
            <%= f.label :unit %>
            <%= f.text_field :unit, class:"form-control" %>
        </p>
        
        <p>
            <%= f.submit 'Create', :class => "btn-primary btn-lg" %>
        </p>
    </div>
</div>
<% end %>

<%= link_to "Back to ingredients listing", ingredients_path %>

app/views/ingredients/_ingredient.html.erb
<tr id="ingredient_<%= ingredient.id %>">
        <td><%= best_in_place ingredient, :name %></td>
        <td><%= best_in_place ingredient, :purchase_price, :display_with => :number_to_currency, :helper_options => {:unit => "RM"} %></td>
        <td><%= best_in_place ingredient, :volume %></td>
        <td><%= best_in_place ingredient, :unit %></td>
        <td><%= number_to_currency(ingredient.price, :unit => "RM") %></td>
        <td><%= ingredient.updated_at %></td>
        <td>
            <%#= link_to 'Edit', edit_ingredient_path(ingredient), :class => 'btn btn-default btn-xs', remote: true  %>
            <%#= link_to 'Show', ingredient_path(ingredient), :class => 'btn btn-default btn-xs' %>
            
            <button type="button" class="btn btn-default btn-xs fa fa-pencil-square-o" data-toggle="modal" data-target="#myupdateingredient_<%= ingredient.id %>">
                
            </button>
            <%= link_to '', ingredient_path(ingredient), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-xs btn-danger fa fa-trash' %>
            <%#= link_to '', ingredient, method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger btn-xs fa fa-trash', remote: true %>
            
            <%= form_for(ingredient, :method => :put, remote: true, :html => {:class => 'form-horizontal'}) do |f| %>
                <div class="modal fade" id="myupdateingredient_<%= ingredient.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Edit Ingredient</h4>
                    </div>
                    <div class="modal-body form-horizontal">
                      
                      <div id="edit_ingredient_error" style="display:none;">
                        <div class="row">
                            <div class="panel panel-danger">
                              <div class="panel-heading">
                                
                                <div class="panel-body">
                                  <div id="edit_ingredient_errors_div"></div>
                                </div>
                              </div>
                            </div>
                        </div>
                      </div>
                      
                        <div class="field">
                          <%= f.label :ingredient_name, class: "col-sm-6"%>
                          <div class="col-sm-6">
                            <%= f.text_field :name, class: "form-control ingredient_name"%>
                          </div>
                        </div><br><br>
                        <div class="field">
                          <%= f.label :purchase_price, class: "col-sm-6" %>
                          <div class="col-sm-6">
                            <%= f.number_field :purchase_price, step: 'any', class:"form-control ingredient_purchase_price" %>
                          </div>
                        </div><br><br>
                        <div class="field">
                          <%= f.label :purchase_weight_or_volume, class: "col-sm-6" %>
                          <div class="col-sm-6">
                            <%= f.number_field :volume, class:"form-control ingredient_volume" %>
                          </div>
                        </div><br><br>
                        <div class="field">
                          <%= f.label :unit, class: "col-sm-6" %>
                          <div class="col-sm-6">
                            <%= f.text_field :unit, class:"form-control ingredient_unit" %>
                          </div>
                        </div><br><br>
                        
                      
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal" id="myupdatebutton_<%= ingredient.id %>">Close</button>
                      <%= submit_tag "Update", class: "btn custom-small-new-button"%>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
        </td>
      </tr>

app/views/ingredients/_lookup.html.erb
<div id="ingredient-lookup">
    <h3>Search for Ingredients</h3>
    <%= form_tag search_ingredients_path, remote: true, method: :get, id: 'ingredient-lookup-form' do %>
    <div class="form-group row no_padding text-center col-md-12">
        <div class="col-md-10">
            <%= text_field_tag :ingredient, params[:ingredient], placeholder: "Ingredient name", autofocus: true,
                                                                        class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
            <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                <i class="fa fa-search"></i> Look up an ingredient</i>
            <% end %>
        </div>
    </div>
    <% end %>
    <%= render 'common/spinner' %>
    <% if !@ingredient.name.nil? %>
        <%#= object do |obj| %>
        <div id="ingredient-lookup-results" class="well results-block">
            <strong>Name:</strong> <%= @ingredient.name %>
            <strong>Purchase Price:</strong> <%= @ingredient.purchase_price %>
            <strong>Unit:</strong> <%= @ingredient.unit %>
            <strong>Price per unit:</strong> <%= @ingredient.price %>
            <%#= link_to "view", recipe_ingredients_path(recipe_id: params[:recipe], ingredient_name: @ingredient.name, 
                ingredient_id: @ingredient.id ? @ingredient.id : ''), class:'btn btn-xs btn-success', method: :post %>
        </div>
        <%# end %>
    <% end %>
    <div id="ingredient-lookup-errors"></div>
</div>

app/views/ingredients/_modal.html.erb
<button type="button" class="btn btn-default btn-xs fa fa-pencil-square-o" data-toggle="modal" data-target="#myupdateingredient_<%= g.id %>">
                
</button>


<div class="modal fade" id="myupdateingredient_<%= g.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <%= form_for(g, :method => :put, remote: true, :html => {:class => 'form-horizontal' }) do |f| %>
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Edit Ingredient</h4>
                    </div>
                    <div class="modal-body">
             
                      <div class="field form-group">
                        <%= f.label :ingredient_name, class: "col-sm-4"%>
                        <div class="col-sm-8">
                          <%= f.text_field :name, class: "form-control ingredient_name"%>
                        </div>
                      </div>
                      <div class="field form-group">
                        <%= f.label :purchase_price, class: "col-sm-4" %>
                        <div class="col-sm-8">
                          <%= f.number_field :purchase_price, step: 'any', class:"form-control ingredient_purchase_price" %>
                        </div>
                      </div>
                      <div class="field form-group">
                        <%= f.label :purchase_weight_or_volume, class: "col-sm-4" %>
                        <div class="col-sm-8">
                          <%= f.number_field :volume, class:"form-control ingredient_volume" %>
                        </div>
                      </div>
                      <div class="field form-group">
                        <%= f.label :unit, class: "col-sm-4" %>
                        <div class="col-sm-8">
                          <%= f.text_field :unit, class:"form-control ingredient_unit" %>
                        </div>
                      </div>
                      
                          <div id="errors_div">
                            
                          </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal" id="myupdatebutton_<%= g.id %>">Close</button>
                      <%= submit_tag "Update", class: "btn btn-primary"%>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>

app/views/ingredients/_popup.html.erb
<div class="container">
  <div class="row">
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal", data-remote="true", data-target="#mynewingredient">
      Create New Ingredient Popup
    </button>
  </div>
  

  
  <!-- Modal -->
      <%= form_for(@ingredient, remote: true, id: 'ingredient-popup-form') do |f| %>
        <div class="modal fade" id="mynewingredient" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Create new Ingredient</h4>
            </div>
            <div class="modal-body">
              <div class="field">
                <%= f.label :ingredient_name%><br>
                <%= f.text_field :name, class: "form-control ingredient_name"%>
              </div>
              <div class="field">
                <%= f.label :purchase_price %>
                <%= f.number_field :purchase_price, step: 'any', class:"form-control ingredient_purchase_price" %>
              </div>
              <div class="field">
                <%= f.label :purchase_weight_or_volume %>
                <%= f.number_field :volume, class:"form-control ingredient_volume" %>
              </div>
              <div class="field">
                <%= f.label :unit %>
                <%= f.text_field :unit, class:"form-control ingredient_unit" %>
              </div>
              <div id="errors_div"></div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewingredientclose">Close</button>
              <%= submit_tag "Create", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <!-- Modal -->
  
</div>

app/views/ingredients/create.js.erb
var ready;
ready = function () {

$('#create_ingredient').click(function(){
    $('.ingredient_name, .ingredient_purchase_price, .ingredient_unit, .ingredient_volume').val("");
    $('#ingredient_errors_div').empty();
    $("#show_ingredient_error").hide();
});



<% if @ingredient.errors.any? %>
    $("#show_ingredient_error").show();
    $('#ingredient_errors_div').empty();
    <% str2 = "The following errors prevented the ingredient from getting created" + "<br/>" %>
    $("#ingredient_errors_div").append("<strong><%= raw j str2 %></strong>");
    <% str = "" %>
    <% @ingredient.errors.full_messages.each do |error| %>
        <% str+= error + "<br/>" %>
    <% end %>
    $("#ingredient_errors_div").append("<%= raw j str %>");
<% else %>
    $("#mynewingredient").modal('hide');
    $(".ingredient_name").val('');
    $(".ingredient_purchase_price").val('');
    $(".ingredient_volume").val('');
    $(".ingredient_unit").val('');
    
    $("#container_ingredients").append('<tr><%= j render @ingredient %></tr>');
    $("#ingredient_<%= @ingredient.id %>").hide().fadeIn(1000);
    $('.best_in_place').best_in_place();
    
    location.reload();
    
    
<% end %>
};

$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('turbolinks:render', ready);

app/views/ingredients/destroy.js.erb
$("#ingredient_<%= @ingredient.id %>").fadeOut(500, function(){
   $(this).remove();
   location.reload();
});

app/views/ingredients/edit.html.erb
<h1>Edit existing ingredient</h1>

<%= render 'form' %>

app/views/ingredients/index.html.erb
    
<div class= "row">
  <div class = "container col-md-10">
    <h1><i class="fa fa-th-list" aria-hidden="true"></i> Ingredients
      <div class = "pull-right">
        <button type="button" class="btn custom-new-button" data-toggle="modal" data-target="#mynewingredient">
          <i class="fa fa-plus" aria-hidden="true"></i> Add Ingredient
        </button>
      </div> 
    </h1>
    
    
    <%= form_for(@ingredient, remote: true, id: 'ingredient-popup-form', :html => {:class => 'form-horizontal'}) do |f| %>
        <div class="modal fade" id="mynewingredient" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Create new Ingredient</h4>
            </div>
            <div class="modal-body">
             <div id="show_ingredient_error" style="display:none;">
                <div class="row">
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        
                        <div class="panel-body">
                          <div id="ingredient_errors_div"></div>
                        </div>
                      </div>
                    </div>
                </div>
              </div>
              <div class="field form-group">
                <%= f.label :ingredient_name, class: "col-sm-4"%>
                <div class="col-sm-8">
                  <%= f.text_field :name, class: "form-control ingredient_name"%>
                </div>
              </div>
              <div class="field form-group">
                <%= f.label :purchase_price, class: "col-sm-4" %>
                <div class="col-sm-8">
                  <%= f.number_field :purchase_price, step: 'any', class:"form-control ingredient_purchase_price" %>
                </div>
              </div>
              <div class="field form-group">
                <%= f.label :purchase_weight_or_volume, class: "col-sm-4" %>
                <div class="col-sm-8">
                  <%= f.number_field :volume, class:"form-control ingredient_volume" %>
                </div>
              </div>
              <div class="field form-group">
                <%= f.label :unit, class: "col-sm-4" %>
                <div class="col-sm-8">
                  <%= f.text_field :unit, class:"form-control ingredient_unit" %>
                </div>
              </div>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewingredientclose">Close</button>
              <%= submit_tag "Create", class: "btn custom-small-new-button" %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      
<div class="panel panel-default">
	<div class="panel-heading panel-heading-custom">
		Ingredient List
	</div>
	<div class="panel-body">
	  <div class="table-responsive">
    	<table id="all_ingredients_list">
        <thead>
        <tr>
            <th>Ingredient Name</th>
            <th>Purchase price</th>
            <th>Purchase weight or volume</th>
            <th>Unit</th>
            <th>Price per single unit</th>
            <th>Last modified</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody id="container_ingredients">
            <%= render @ingredients %>
        </tbody>
      </table>
      </div>
	</div>
</div>

</div>
</div>

app/views/ingredients/new.html.erb
<h1>Add an ingredient</h1>

<%= render 'form' %>

app/views/ingredients/new.js.erb
$('#new_link').hide()

app/views/ingredients/show.html.erb
<h1>Showing selected ingredient</h1>


    <p><strong>Ingredient name:</strong> <%= @ingredient.name %></p>


    <p><strong>Purchase price: </strong> <%= number_to_currency(@ingredient.purchase_price, :unit => "RM") %></p>

    <p><strong>Purchased weight or volume: </strong><%= @ingredient.volume %></p>

    <p><strong>Unit:</strong><%= @ingredient.unit %></p>
    
    <p><strong>Price per single unit: </strong> <%= number_to_currency(@ingredient.price, :unit => "RM") %></p>


<%= link_to t('.back', :default => t("helpers.links.back")),
              ingredients_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ingredient_path(@ingredient), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ingredient_path(@ingredient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/ingredients/update.js.erb
var ready;
ready = function () {

$('#edit_ingredient').click(function(){
    $('#edit_ingredient_errors_div').empty();
    $("#edit_ingredient_error").hide();
});




<% if @ingredient.errors.any? %>
   
    $("#edit_ingredient_error").show();
    $('#edit_ingredient_errors_div').empty();
    <% str2 = "The following errors prevented the ingredient from getting changes" + "<br/>" %>
    $("#edit_ingredient_errors_div").append("<strong><%= raw j str2 %></strong>");
    <% str = "" %>
    <% @ingredient.errors.full_messages.each do |error| %>
        <% str+= error + "<br/>" %>
    <% end %>
    $("#edit_ingredient_errors_div").append("<%= raw j str %>");
<% else %>
    $("#edit_ingredient_error").hide();
    $("#myupdateingredient_<%= @ingredient.id %>").modal('hide');

      $("#ingredient_<%= @ingredient.id %>").fadeOut(500, function(){
         $(this).remove();
         $("#container_ingredients").append('<tr><%= j render @ingredient %></tr>');
      });
      location.reload();
<% end %>

};
$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('turbolinks:render', ready);