config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "user/registrations" }

  
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#dashboard', as: :authenticated_root
    end
    
    
    
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  root 'devise/sessions#new'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_users', to: 'pages#all_users'
  get 'my_recipes', to: "recipes#my_recipes"
  get 'search_ingredients', to: "ingredients#search"
  get 'search_materials', to: "materials#search"
  
  get "recipe/new_release" => 'recipe#new_release', :as => :new_release
  
  resources :ingredients
  
  resources :recipes
    
  resources :recipe_ingredients

  resources :overheads
  
  resources :materials
  
  resources :recipe_materials
  
  resources :users#, only: [:index, :edit, :update]

end

app/views/pages/about.html.erb
<h1>About us</h1>

<%= link_to 'Homes', root_path %>

app/views/pages/dashboard.html.erb
<%- model_class = Recipe -%>
<h1><i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard</h1>
<div class="row">
    <div class="col-md-3 blog-main box text-center">
        <div class="panel panel-default">
        	<div class="panel-heading panel-heading-dashboard">
        		<h4>Total Recipe</h4>
        		<h2 class="white"><%= current_user.recipes.count %></h2>
        	</div>
        	<div class="panel-body">
            	<%= link_to ' View Details', recipes_path, class: "fa fa-arrow-circle-right" %>
        	</div>
        </div>
    </div>
    <div class="col-md-3 blog-main box text-center">
        <div class="panel panel-default">
        	<div class="panel-heading panel-heading-dashboard">
        		<h4>Total Ingredient</h4>
        		<h2 class="white"><%= current_user.ingredients.count %></h2>
        	</div>
        	<div class="panel-body">
            	<%= link_to ' View Details', ingredients_path, class: "fa fa-arrow-circle-right" %>
        	</div>
        </div>
    </div>
    <div class="col-md-3 blog-main box text-center">
        <div class="panel panel-default">
        	<div class="panel-heading panel-heading-dashboard">
        		<h4>Total Non-food Items</h4>
        		<h2 class="white"><%= current_user.materials.count %></h2>
        	</div>
        	<div class="panel-body">
            	<%= link_to ' View Details', materials_path, class: "fa fa-arrow-circle-right" %>
        	</div>
        </div>
    </div>
    <div class="col-md-3 blog-main box text-center">
        <div class="panel panel-default">
        	<div class="panel-heading panel-heading-dashboard">
        		<h4>My Overheads Cost per Hour</h4>
        		<h2 class="white"><%= number_to_currency(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f), :unit => "RM") %></h2>
        	</div>
        	<div class="panel-body">
            	<%= link_to ' View Details', overheads_path, class: "fa fa-arrow-circle-right" %>
        	</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="container col-md-12">
          <div class="panel panel-default">
      	<div class="panel-heading panel-heading-custom">
      		List of Recipes
      	</div>
      	<div class="panel-body">
      	  <div class="table-responsive">
          <table class="table" id="recipes">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th>Ingredients Cost</th>
                <th>Non-food item cost (Materials)</th>
                <th>Grant cost of Recipe</th>
                <th>Labour Cost</th>
                <th>Recipe cost</th>
                <th>Profit to add to price:</th>
                <th>TOTAL cost of RECIPE(S) including profit:</th>
                <th>Number of serving</th>
                <th>Cost per serving</th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @recipes.each do |recipe| %>
                <tr>
                  <% @recipe = Recipe.includes(:recipe_ingredients).find(recipe.id) %>
                  <% @recipe.calculate_cost %>
                  <% @recipe.calculate_material_cost %>
                  <td><%= link_to recipe.title, recipe_path(recipe) %></td>
                  <td><%= number_to_currency(@recipe.cost, :unit => "RM") %></td>
                  <td><%= number_to_currency(@recipe.material_cost, :unit => "RM") %></td>
                  <td><%= number_to_currency(@recipe.cost.to_f + @recipe.material_cost.to_f, :unit => "RM") %></td>
                  
                  
                        
                            
                            <td><% @labour = ((recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*recipe.time_spent_in_hour.to_f) %>
                            <%= number_to_currency(@labour, :unit => "RM") %>
                            </td>
                        
                            
                            <td><% @cake_cost = (recipe.cost.to_f + recipe.material_cost.to_f + ((recipe.rate_per_hour.to_f+(current_user.overheads.sum(:total)/((52-current_user.no_of_week_holiday_per_year.to_f)*current_user.hour_worked_per_week.to_f)))*recipe.time_spent_in_hour.to_f)) %>
                            <%= number_to_currency(@cake_cost, :unit => "RM") %>
                            </td>
                       
                            
                            <td><% @profit = (recipe.percentage_profit.to_f/100)*@cake_cost.to_f %>
                            <%= number_to_currency(@profit, :unit => "RM") %>
                            </td>
                        
                            <% @total = @profit.to_f + @cake_cost.to_f %>
                            
                            <td><%= number_to_currency(@total, :unit => "RM") %></td>
                        
                            
                            <td><%= recipe.serving_number %></td>
                        
                            
                            <td><%= number_to_currency(@total.to_f / recipe.serving_number.to_f, :unit => "RM") %></td>
                                          
                  
                  <td>
                          
                    <%= link_to '', edit_recipe_path(recipe), :class => 'btn btn-default btn-xs fa fa-pencil-square-o'%>
                    <%= link_to '', recipe_path(recipe), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-xs btn-danger fa fa-trash' %>
                    
                    <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                recipe_path(recipe),
                                :method => :delete,
                                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                :class => 'btn btn-xs btn-danger' %>
                  </td>
                </tr>
          
              <% end %>
            </tbody>
          </table>
          </div>
      	</div>
      </div>
      </div>
</div>

app/views/pages/home.html.erb
<h1>This is my homepage</h1>


<div class="login-clean">
        <form method="post">
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="icon ion-ios-navigate"></i></div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Log In</button>
            </div><a href="#" class="forgot">Forgot your email or password?</a></form>
    </div>