config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "user/registrations" }

  
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#dashboard', as: :authenticated_root
    end
    
    
    
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  root 'devise/sessions#new'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_users', to: 'pages#all_users'
  get 'my_recipes', to: "recipes#my_recipes"
  get 'search_ingredients', to: "ingredients#search"
  get 'search_materials', to: "materials#search"
  
  get "recipe/new_release" => 'recipe#new_release', :as => :new_release
  
  resources :ingredients
  
  resources :recipes
    
  resources :recipe_ingredients

  resources :overheads
  
  resources :materials
  
  resources :recipe_materials
  
  resources :users#, only: [:index, :edit, :update]

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> 
    <ul>
      <li><%= msg %></li>
    </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<% if current_user  %>
<div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"><%= link_to 'Recipe Management', root_path, class: "navbar-brand" %></li>
                <li><%= menu_item "Recipe", recipes_path %></li>
                <li><%= menu_item "Ingredient", ingredients_path %></li>
                <li><%= menu_item "Overhead", overheads_path %></li>
                <li><%= link_to "My Profile", edit_registration_path(current_user)  %></li>
            </ul>
        </div> 
        <div class="page-content-wrapper">
                <div class="row">
                    <div class="col-md-9">
                        <div class="page-header">
                                 <div class="navbar navbar-default navbar-static-top">
                                  <div class="container">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                                          <span class="icon-bar"></span>
                                          <span class="icon-bar"></span>
                                          <span class="icon-bar"></span>
                                        </button>
                                   <div class="navbar-collapse collapse navbar-responsive-collapse">
                                      <ul class="nav navbar-nav col-md-6">
                                        <%#= menu_item "Recipe", recipes_path %>
                                        <%#= menu_item "Overhead", overheads_path %>
                                        <li><%#= link_to "My Profile", edit_registration_path(current_user)  %></li>
                                        
                                      </ul>
                                      <ul class="nav navbar-right col-md-4">
                                        <li class="col-md-4 user-name text-right">
                                          <i class="fa fa-user"></i>
                                          <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
                                        </li>
                                        <li class="col-md-4 logout"><%= link_to "logout", destroy_user_session_path, class: 'btn btn-xs btn-danger', method: :delete %></li>
                                      </ul>
                                    </div>
                                   </div>
                                 </div>    
                          </div>
                            <%= bootstrap_flash %>
                            <%= yield %>
                </div>
            </div>
        </div>
    </div>
<% else %>

  <div class="row">
          <div class="col-lg-6 col-centered">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <%= csrf_meta_tags %>
    
    
    <!-- modal test -->
      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      
      <!-- Optional theme -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      
      <!-- Latest compiled and minified JavaScript -->
 
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   <!-- modal test -->


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "rails.validations", "rails.validations.simple_form"  %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%#= render 'layouts/navigation' %>

  
      <% if current_user %>
      <div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"><%= link_to 'Bake for Cash', root_path, class: "navbar-brand" %></li>
                <li class="divider"></li>
                <li><%= menu_item "Dashboard", root_path %></li>
                <% if current_user.admin? %>
                <li><%= menu_item "All Users", users_path %></li>
                <% end %>
                <li><%= menu_item "Recipe", recipes_path %></li>
                <li><%= menu_item "Ingredient", ingredients_path %></li>
                <li><%= menu_item "Material", materials_path %></li>
                <li><%= menu_item "Overhead", overheads_path %></li>
                <li><%= link_to "My Profile", edit_registration_path(current_user)  %></li>
                <li class="divider"></li>
              </ul>
        </div>
        <% end %>
        <div class="page-content-wrapper">
            <div class="container-fluid">
                <% if current_user %>
                <a class="btn btn-link" role="button" href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars"></i></a>
                
                <% end %>
                <div class="row">
                    <div class="col-lg-12">
                      <div class="row">
                          <div class="pull-right">
                            <% if current_user %>
                              <i class="fa fa-user"></i><%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
                              <%= link_to " Logout ", destroy_user_session_path, class: 'btn btn-default fa fa-sign-out logout-button', method: :delete %>
                            <% else %>
                              <%= link_to ' Login ', new_user_session_path, class: 'btn btn-default fa fa-sign-in' %>
                            <% end %>
                          </div>
                      </div>
                        <%= bootstrap_flash %>
                        <%= yield %>
                        <footer>
                          <p>&copy; Final Year Project Huzaifah 2016</p>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>